export const SECTIONS = "SECTIONS";
export const ADDSECTION = "ADDSECTION";
export const EDITSECTION = "EDITSECTION";
export const SETCURRENTSECTION = "SETCURRENTSECTION";
export const EMPTYSECTION = "EMPTYSECTION";